/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#EFE0EC",
        "on-primary-fixed": "#26142f",
        "error": "#ba1a1a",
        "on-tertiary-fixed-variant": "#533f60",
        "secondary-fixed-dim": "#c8c5cb",
        "tertiary": "#150422",
        "royal-violet": "#982476",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#543f5d",
        "surface-container-low": "#FDF2FA",
        "tertiary-fixed": "#f3daff",
        "on-secondary-container": "#656369",
        "inverse-surface": "#352e37",
        "secondary": "#5f5e63",
        "on-error-container": "#93000a",
        "surface-dim": "#e3d6e2",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#9881a6",
        "surface-tint": "#982476",
        "inverse-primary": "#d8bde1",
        "on-tertiary-fixed": "#261432",
        "primary-container": "#3D1437",
        "outline-variant": "#cdc4cc",
        "inverse-on-surface": "#faedf9",
        "primary": "#180516",
        "on-secondary-fixed": "#1c1b1f",
        "lavender-mist": "#F4E3F1",
        "on-surface-variant": "#4b454c",
        "tertiary-container": "#2d1a39",
        "plum-deep": "#260A22",
        "on-secondary-fixed-variant": "#47464b",
        "surface-container-high": "#F5E5F2",
        "amethyst-soft": "#C76AA9",
        "secondary-fixed": "#e5e1e7",
        "surface": "#FFF7FC",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "on-background": "#201922",
        "tertiary-fixed-dim": "#d8bde6",
        "on-primary-container": "#9981a2",
        "secondary-container": "#e5e1e7",
        "primary-fixed": "#f5d9fe",
        "outline": "#7c757c",
        "background": "#FFF7FC",
        "surface-container": "#FAF0F8",
        "surface-bright": "#FFF7FC",
        "on-surface": "#201922",
        "surface-container-highest": "#EFE0EC",
        "primary-fixed-dim": "#d8bde1",
        "on-error": "#ffffff",
        "gold-accent": "#D4AF37",
        "gold-soft": "#F3E5AB"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "0.125rem",
        md: "0.25rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        "container-max": "1440px",
        "mobile-margin": "20px",
        "grid-gutter": "24px",
        "section-gap": "120px",
        "content-margin": "64px"
      },
      fontFamily: {
        "body-lg": ["Manrope", "sans-serif"],
        "body-md": ["Manrope", "sans-serif"],
        "headline-lg": ["Playfair Display", "serif"],
        "display-lg": ["Playfair Display", "serif"],
        "label-sm": ["Manrope", "sans-serif"],
        "headline-md": ["Playfair Display", "serif"],
        "headline-lg-mobile": ["Playfair Display", "serif"],
        "serif": ["Playfair Display", "Georgia", "serif"],
        "sans": ["Manrope", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg": ["40px", { lineHeight: "1.2", fontWeight: "500" }],
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "600" }],
        "headline-md": ["28px", { lineHeight: "1.3", fontWeight: "500" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "500" }]
      },
      boxShadow: {
        'luxury': '0px 10px 40px rgba(74, 44, 42, 0.05)',
        'luxury-lg': '0 30px 60px -15px rgba(21, 5, 30, 0.12)',
        'subtle': '0 2px 10px rgba(0, 0, 0, 0.03)',
        'glow': '0 0 25px rgba(152, 36, 118, 0.28)'
      }
    },
  },
  plugins: [],
}
